part of 'themes.dart';

/// sets the dark theme of the app
final ThemeData darkTheme = FlexThemeData.dark(
  colors: const FlexSchemeColor(
    primary: Color(0xff004953),
    primaryContainer: Color(0xff087e8b),
    secondary: Color(0xff3f88c5),
    secondaryContainer: Color(0xffb7d1da),
    tertiary: Color(0xff625834),
    tertiaryContainer: Color(0xffa59132),
    appBarColor: Color(0xffb7d1da),
    error: Color(0xffcf6679),
  ),
  surfaceMode: FlexSurfaceMode.highBackgroundLowScaffold,
  blendLevel: 8,
  subThemesData: const FlexSubThemesData(
    blendOnLevel: 8,
    blendTextTheme: true,
    useTextTheme: true,
    useM2StyleDividerInM3: true,
    splashType: FlexSplashType.noSplash,
    adaptiveAppBarScrollUnderOff: FlexAdaptive.all(),
    defaultRadius: 8,
    outlinedButtonOutlineSchemeColor: SchemeColor.primary,
    outlinedButtonPressedBorderWidth: 2,
    toggleButtonsBorderSchemeColor: SchemeColor.primary,
    segmentedButtonSchemeColor: SchemeColor.primary,
    segmentedButtonBorderSchemeColor: SchemeColor.primary,
    unselectedToggleIsColored: true,
    sliderValueTinted: true,
    inputDecoratorSchemeColor: SchemeColor.primary,
    inputDecoratorIsFilled: false,
    inputDecoratorBackgroundAlpha: 43,
    inputDecoratorRadius: 8,
    inputDecoratorUnfocusedBorderIsColored: false,
    popupMenuRadius: 6,
    popupMenuElevation: 8,
    useInputDecoratorThemeInDialogs: true,
    drawerIndicatorSchemeColor: SchemeColor.primary,
    bottomNavigationBarMutedUnselectedLabel: false,
    bottomNavigationBarMutedUnselectedIcon: false,
    menuRadius: 6,
    menuElevation: 8,
    menuBarRadius: 0,
    menuBarElevation: 1,
    navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
    navigationBarMutedUnselectedLabel: false,
    navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
    navigationBarMutedUnselectedIcon: false,
    navigationBarIndicatorSchemeColor: SchemeColor.primary,
    navigationBarIndicatorOpacity: 1,
    navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
    navigationRailMutedUnselectedLabel: false,
    navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
    navigationRailMutedUnselectedIcon: false,
    navigationRailIndicatorSchemeColor: SchemeColor.primary,
    navigationRailIndicatorOpacity: 1,
    buttonPadding: EdgeInsets.symmetric(horizontal: 16, vertical: 20),
    buttonMinSize: Size(64, 48),
  ),
  useMaterial3ErrorColors: true,
  visualDensity: VisualDensity.compact,
  useMaterial3: true,
  fontFamily: 'Gilroy',
);
